/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package book4u;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author Daniel
 */
public class PaginaHistorial extends javax.swing.JPanel {

    /**
     * Creates new form PaginaHistorial
     */
    public PaginaHistorial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LesMevesReserves = new javax.swing.JButton();
        BotonPaginaPrincipal = new javax.swing.JButton();
        BotonNovaReserva = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LesMevesReserves.setBorder(null);
        LesMevesReserves.setBorderPainted(false);
        LesMevesReserves.setContentAreaFilled(false);
        LesMevesReserves.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LesMevesReserves.setFocusable(false);
        LesMevesReserves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LesMevesReservesActionPerformed(evt);
            }
        });
        add(LesMevesReserves, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, 290, 90));

        BotonPaginaPrincipal.setBorder(null);
        BotonPaginaPrincipal.setBorderPainted(false);
        BotonPaginaPrincipal.setContentAreaFilled(false);
        BotonPaginaPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonPaginaPrincipal.setFocusable(false);
        BotonPaginaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPaginaPrincipalActionPerformed(evt);
            }
        });
        add(BotonPaginaPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 40, 230, 90));

        BotonNovaReserva.setBorder(null);
        BotonNovaReserva.setBorderPainted(false);
        BotonNovaReserva.setContentAreaFilled(false);
        BotonNovaReserva.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonNovaReserva.setFocusable(false);
        BotonNovaReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonNovaReservaActionPerformed(evt);
            }
        });
        add(BotonNovaReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 220, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/PaginaHistorial.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void LesMevesReservesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LesMevesReservesActionPerformed
        JFrame marco = (JFrame) SwingUtilities.getWindowAncestor(this);
        marco.remove(this);
        marco.add(new PaginaMevesReservesPanel ());
        marco.setVisible(true);
    }//GEN-LAST:event_LesMevesReservesActionPerformed

    private void BotonPaginaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPaginaPrincipalActionPerformed
        JFrame marco = (JFrame) SwingUtilities.getWindowAncestor(this);
        marco.remove(this);
        marco.add(new PaginaPrincipalPanel ());
        marco.setVisible(true);
    }//GEN-LAST:event_BotonPaginaPrincipalActionPerformed

    private void BotonNovaReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonNovaReservaActionPerformed
        JFrame marco = (JFrame) SwingUtilities.getWindowAncestor(this);
        marco.remove(this);
        marco.add(new PaginaReservaPanel ());
        marco.setVisible(true);
    }//GEN-LAST:event_BotonNovaReservaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonNovaReserva;
    private javax.swing.JButton BotonPaginaPrincipal;
    private javax.swing.JButton LesMevesReserves;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
