/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package book4u;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author Usuario
 */
public class PaginaReservaPanel extends javax.swing.JPanel {

    /**
     * Creates new form PaginaReservaPanel
     */
    public PaginaReservaPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonReserva = new javax.swing.JButton();
        BotonPaginaPrincipal = new javax.swing.JButton();
        BotonMonedero = new javax.swing.JButton();
        BotonHistorial = new javax.swing.JButton();
        BotonUsuario = new javax.swing.JButton();
        BotonCrearReserva = new javax.swing.JButton();
        BotonCrearReserva1 = new javax.swing.JButton();
        BotonCrearReserva2 = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonReserva.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BotonReserva.setBorder(null);
        BotonReserva.setBorderPainted(false);
        BotonReserva.setContentAreaFilled(false);
        BotonReserva.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonReserva.setFocusable(false);
        BotonReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonReservaActionPerformed(evt);
            }
        });
        add(BotonReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 220, 100));

        BotonPaginaPrincipal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BotonPaginaPrincipal.setBorder(null);
        BotonPaginaPrincipal.setBorderPainted(false);
        BotonPaginaPrincipal.setContentAreaFilled(false);
        BotonPaginaPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonPaginaPrincipal.setFocusPainted(false);
        BotonPaginaPrincipal.setFocusable(false);
        BotonPaginaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPaginaPrincipalActionPerformed(evt);
            }
        });
        add(BotonPaginaPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, 230, 90));

        BotonMonedero.setBorder(null);
        BotonMonedero.setBorderPainted(false);
        BotonMonedero.setContentAreaFilled(false);
        BotonMonedero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonMonedero.setFocusable(false);
        add(BotonMonedero, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 30, 210, 110));

        BotonHistorial.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BotonHistorial.setBorder(null);
        BotonHistorial.setBorderPainted(false);
        BotonHistorial.setContentAreaFilled(false);
        BotonHistorial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonHistorial.setFocusable(false);
        BotonHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonHistorialActionPerformed(evt);
            }
        });
        add(BotonHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 40, 220, 90));

        BotonUsuario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BotonUsuario.setBorder(null);
        BotonUsuario.setBorderPainted(false);
        BotonUsuario.setContentAreaFilled(false);
        BotonUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonUsuario.setFocusable(false);
        BotonUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonUsuarioActionPerformed(evt);
            }
        });
        add(BotonUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1760, 30, 110, 110));

        BotonCrearReserva.setBorder(null);
        BotonCrearReserva.setBorderPainted(false);
        BotonCrearReserva.setContentAreaFilled(false);
        BotonCrearReserva.setFocusable(false);
        BotonCrearReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCrearReservaActionPerformed(evt);
            }
        });
        add(BotonCrearReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(1540, 410, 220, 100));

        BotonCrearReserva1.setBorder(null);
        BotonCrearReserva1.setBorderPainted(false);
        BotonCrearReserva1.setContentAreaFilled(false);
        BotonCrearReserva1.setFocusable(false);
        BotonCrearReserva1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCrearReserva1ActionPerformed(evt);
            }
        });
        add(BotonCrearReserva1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1540, 640, 220, 100));

        BotonCrearReserva2.setBorder(null);
        BotonCrearReserva2.setBorderPainted(false);
        BotonCrearReserva2.setContentAreaFilled(false);
        BotonCrearReserva2.setFocusable(false);
        BotonCrearReserva2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCrearReserva2ActionPerformed(evt);
            }
        });
        add(BotonCrearReserva2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1540, 870, 220, 100));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/PaginaReserva.png"))); // NOI18N
        add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void BotonReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonReservaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonReservaActionPerformed

    private void BotonPaginaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPaginaPrincipalActionPerformed
        // TODO add your handling code here:
        JFrame marco = (JFrame) SwingUtilities.getWindowAncestor(this);
        marco.remove(this);
        marco.add(new PaginaPrincipalPanel ());
        marco.setVisible(true);
    }//GEN-LAST:event_BotonPaginaPrincipalActionPerformed

    private void BotonHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonHistorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonHistorialActionPerformed

    private void BotonUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonUsuarioActionPerformed
        // TODO add your handling code here:
        JFrame marco = (JFrame) SwingUtilities.getWindowAncestor(this);
        marco.remove(this);
        marco.add(new PaginaPerfilUsuario ());
        marco.setVisible(true);
    }//GEN-LAST:event_BotonUsuarioActionPerformed

    private void BotonCrearReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCrearReservaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonCrearReservaActionPerformed

    private void BotonCrearReserva1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCrearReserva1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonCrearReserva1ActionPerformed

    private void BotonCrearReserva2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCrearReserva2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonCrearReserva2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCrearReserva;
    private javax.swing.JButton BotonCrearReserva1;
    private javax.swing.JButton BotonCrearReserva2;
    private javax.swing.JButton BotonHistorial;
    private javax.swing.JButton BotonMonedero;
    private javax.swing.JButton BotonPaginaPrincipal;
    private javax.swing.JButton BotonReserva;
    private javax.swing.JButton BotonUsuario;
    private javax.swing.JLabel Fondo;
    // End of variables declaration//GEN-END:variables
}
