/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package book4u;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;


/**
 *
 * @author xavic
 */
public class PaginaPrincipalPanel extends javax.swing.JPanel {

    /**
     * Creates new form PaginaPrincipalPanel
     */
    public PaginaPrincipalPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBotonNovaReserva = new javax.swing.JButton();
        jBotonLesMevesReserves = new javax.swing.JButton();
        jBotonHistorial1 = new javax.swing.JButton();
        jBotonMonedero = new javax.swing.JButton();
        jBotonUsuario = new javax.swing.JButton();
        jFondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBotonNovaReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Boton_NuevaReserva_PaginaPrincipal.png"))); // NOI18N
        jBotonNovaReserva.setBorderPainted(false);
        jBotonNovaReserva.setContentAreaFilled(false);
        jBotonNovaReserva.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBotonNovaReserva.setFocusPainted(false);
        jBotonNovaReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonNovaReservaActionPerformed(evt);
            }
        });
        add(jBotonNovaReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 230, 100));

        jBotonLesMevesReserves.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Boton_MisReservas_PaginaPrincipal.png"))); // NOI18N
        jBotonLesMevesReserves.setBorder(null);
        jBotonLesMevesReserves.setBorderPainted(false);
        jBotonLesMevesReserves.setContentAreaFilled(false);
        jBotonLesMevesReserves.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBotonLesMevesReserves.setFocusPainted(false);
        jBotonLesMevesReserves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonLesMevesReservesActionPerformed(evt);
            }
        });
        add(jBotonLesMevesReserves, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 310, 110));

        jBotonHistorial1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Boton_Historial_PaginaPrincipal.png"))); // NOI18N
        jBotonHistorial1.setBorder(null);
        jBotonHistorial1.setBorderPainted(false);
        jBotonHistorial1.setContentAreaFilled(false);
        jBotonHistorial1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBotonHistorial1.setFocusPainted(false);
        add(jBotonHistorial1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 40, -1, -1));

        jBotonMonedero.setBorder(null);
        jBotonMonedero.setBorderPainted(false);
        jBotonMonedero.setContentAreaFilled(false);
        jBotonMonedero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBotonMonedero.setFocusable(false);
        add(jBotonMonedero, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 30, 210, 110));

        jBotonUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/perfil.png"))); // NOI18N
        jBotonUsuario.setBorder(null);
        jBotonUsuario.setBorderPainted(false);
        jBotonUsuario.setContentAreaFilled(false);
        jBotonUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBotonUsuario.setFocusPainted(false);
        jBotonUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonUsuarioActionPerformed(evt);
            }
        });
        add(jBotonUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1760, 30, -1, -1));

        jFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Fondo_PaginaPrincipal.png"))); // NOI18N
        add(jFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jBotonNovaReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonNovaReservaActionPerformed
        // TODO add your handling code here:
        JFrame marco = (JFrame) SwingUtilities.getWindowAncestor(this);
        marco.remove(this);
        marco.add(new PaginaReservaPanel ());
        marco.setVisible(true);
    }//GEN-LAST:event_jBotonNovaReservaActionPerformed

    private void jBotonLesMevesReservesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonLesMevesReservesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBotonLesMevesReservesActionPerformed

    private void jBotonUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonUsuarioActionPerformed
       // TODO add your handling code here:
        JFrame marco = (JFrame) SwingUtilities.getWindowAncestor(this);
        marco.remove(this);
        marco.add(new PaginaPerfilUsuario ());
        marco.setVisible(true);
    }//GEN-LAST:event_jBotonUsuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBotonHistorial1;
    private javax.swing.JButton jBotonLesMevesReserves;
    private javax.swing.JButton jBotonMonedero;
    private javax.swing.JButton jBotonNovaReserva;
    private javax.swing.JButton jBotonUsuario;
    private javax.swing.JLabel jFondo;
    // End of variables declaration//GEN-END:variables
}
