/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package book4u;

/**
 *
 * @author xavic
 */
public class PaginaPrincipalPanel extends javax.swing.JPanel {

    /**
     * Creates new form PaginaPrincipalPanel
     */
    public PaginaPrincipalPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBotonNovaReserva = new javax.swing.JButton();
        jBotonLesMevesReserves = new javax.swing.JButton();
        jBotonHistorial = new javax.swing.JButton();
        jFondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBotonNovaReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Boton_NuevaReserva_PaginaPrincipal.png"))); // NOI18N
        jBotonNovaReserva.setBorderPainted(false);
        jBotonNovaReserva.setContentAreaFilled(false);
        jBotonNovaReserva.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBotonNovaReserva.setFocusPainted(false);
        jBotonNovaReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonNovaReservaActionPerformed(evt);
            }
        });
        add(jBotonNovaReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 230, 100));

        jBotonLesMevesReserves.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Boton_MisReservas_PaginaPrincipal.png"))); // NOI18N
        jBotonLesMevesReserves.setBorder(null);
        jBotonLesMevesReserves.setBorderPainted(false);
        jBotonLesMevesReserves.setContentAreaFilled(false);
        jBotonLesMevesReserves.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBotonLesMevesReserves.setFocusPainted(false);
        jBotonLesMevesReserves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonLesMevesReservesActionPerformed(evt);
            }
        });
        add(jBotonLesMevesReserves, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 310, 110));

        jBotonHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Boton_Historial_PaginaPrincipal.png"))); // NOI18N
        jBotonHistorial.setBorder(null);
        jBotonHistorial.setBorderPainted(false);
        jBotonHistorial.setContentAreaFilled(false);
        jBotonHistorial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBotonHistorial.setFocusPainted(false);
        add(jBotonHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 40, -1, -1));

        jFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Fondo_PaginaPrincipal.png"))); // NOI18N
        add(jFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jBotonNovaReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonNovaReservaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBotonNovaReservaActionPerformed

    private void jBotonLesMevesReservesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonLesMevesReservesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBotonLesMevesReservesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBotonHistorial;
    private javax.swing.JButton jBotonLesMevesReserves;
    private javax.swing.JButton jBotonNovaReserva;
    private javax.swing.JLabel jFondo;
    // End of variables declaration//GEN-END:variables
}
